### ISSUE TITLE
ImportError: libfreenect2.so.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MakerStuff** [rjw57/freenect2-python#6]
I got this error and don't know how to fix it.
```
>>> from freenect2 import Device
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/path/to/jetbrains/pycharm/pycharm-community-2020.2.2/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/path/to/project_name/venv/lib/python3.8/site-packages/freenect2/__init__.py", line 10, in <module>
    from ._freenect2 import lib, ffi
  File "/path/to/jetbrains/pycharm/pycharm-community-2020.2.2/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: libfreenect2.so.0.2: cannot open shared object file: No such file or directory
```
> Personal data has been replaced

The error is also thrown when importing `FrameType` instead of `Device`.

libfreenect2 is installed as described in https://github.com/OpenKinect/libfreenect2#linux on Ubuntu 20.04

`$HOME/libfreenect2/build/bin/Protonect` works.
`pip install pylibfreenect2` failed as well. I don't know if that is related.

Can anyone help me out on that?

**Comment by oldbane** [comment]
@MakerStuff this kind of error means that the object file is missing from the include paths. There's a couple ways to address it, for instance by adding the path to the library file in the list of include paths of the program you are trying to run. This can be a bit of a pain and also wouldn't fix it for all other programs that might have this same issue. 

     
However, another (possibly better) solution is to simply link the missing library into one of the places that is already in your include path, `/usr/lib` being a good one.

Try `sudo ln -s $HOME/freenect2/lib/libfreenect2.so.0.2 /usr/lib/libfreenect2.so.0.2` to link it. This should make a symbol link from the libfreenect2 shared object file, as long as it exists at `$HOME/freenect2/lib/libfreenect2.so.0.2`.


P.S. Another tip is if you are unsure where a file exists (or if you even have it), such as the `libfreenect2.so.0.2` file here, you can search for where it is at by doing `find $HOME | grep libfreenect2.so.0.2`, where `$HOME` is the location you'd like to search recursively.

**Comment by MakerStuff** [comment]
Thank you very much for that detailed answer.

The examples at https://rjw57.github.io/freenect2-python/ worked fine.

**Comment by oscarmarinoa** [comment]
When I execute "sudo ln -s $HOME/freenect2/lib/libfreenect2.so.0.2 /usr/lib/libfreenect2.so.0.2" dependencies are found, nevertheless the sensor gives back an image that is frozen, it does not show real time sensing. Any suggestion?
